export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS'
export const SET_SUBSCRIPTIONS_LOADING_STATE = 'SET_SUBSCRIPTIONS_LOADING_STATE'

export const SET_CURRENT_SUBSCRIPTION = 'SET_CURRENT_SUBSCRIPTION'
export const SET_CURRENT_SUBSCRIPTION_LOADING_STATE = 'SET_CURRENT_SUBSCRIPTION_LOADING_STATE'
export const CLEAR_CURRENT_SUBSCRIPTION = 'CLEAR_CURRENT_SUBSCRIPTION'

export const SET_SELECTED_NODE = 'SET_SELECTED_NODE'
export const CLEAR_SELECTED_NODE = 'CLEAR_SELECTED_NODE'
export const SET_CONNECTED_NODE = 'SET_CONNECTED_NODE'
export const CLEAR_CONNECTED_NODE = 'CLEAR_CONNECTED_NODE'
export const SET_DEFAULT_NODE_LOADING_STATE = 'SET_DEFAULT_NODE_LOADING_STATE'

export const SET_PAYMENT_LOADING_STATE = 'SET_PAYMENT_LOADING_STATE'
export const SET_PAYMENT_RESULT = 'SET_PAYMENT_RESULT'
export const CLEAR_PAYMENT_RESULT = 'CLEAR_PAYMENT_RESULT'

export const SET_CONNECTION_STATE = 'SET_CONNECTION_STATE'
export const SET_CONNECTION_LOADING_STATE = 'SET_CONNECTION_LOADING_STATE'
export const SET_CURRENT_IP = 'SET_CURRENT_IP'
export const SET_CURRENT_IP_LOADING_STATE = 'SET_CURRENT_IP_LOADING_STATE'
export const CLEAR_CURRENT_IP = 'CLEAR_CURRENT_IP'
export const SET_SERVICE_SERVER_STATE = 'SET_SERVICE_SERVER_STATE'

export const SET_QUOTA = 'SET_QUOTA'
export const SET_QUOTA_LOADING_STATE = 'SET_QUOTA_LOADING_STATE'
export const CLEAR_QUOTA = 'CLEAR_QUOTA'

export const SET_NODES = 'SET_NODES'
export const SET_NODES_LOADING_STATE = 'SET_NODES_LOADING_STATE'
export const SET_SUBSCRIBED_NODES = 'SET_SUBSCRIBED_NODES'
export const SET_SUBSCRIBED_NODES_LOADING_STATE = 'SET_SUBSCRIBED_NODES_LOADING_STATE'

export const SET_USER = 'SET_USER'
export const SET_USER_LOADING_STATE = 'SET_USER_LOADING_STATE'

export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN'
export const SET_SELECTED_CRYPTO = 'SET_SELECTED_CRYPTO'
export const CLEAR_SELECTED_PLAN = 'CLEAR_SELECTED_PLAN'

export const SET_BALANCES = 'SET_BALANCES'

export const SET_SELECTED_DNS = 'SET_SELECTED_DNS'
export const CLEAR_SELECTED_DNS = 'CLEAR_SELECTED_DNS'
