export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS'
export const SET_SUBSCRIPTIONS_LOADING_STATE = 'SET_SUBSCRIPTIONS_LOADING_STATE'

export const SET_CURRENT_SUBSCRIPTION = 'SET_CURRENT_SUBSCRIPTION'
export const SET_CURRENT_SUBSCRIPTION_LOADING_STATE = 'SET_CURRENT_SUBSCRIPTION_LOADING_STATE'

export const SET_SELECTED_NODE = 'SET_SELECTED_NODE'
