export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS'
export const SET_SUBSCRIPTIONS_LOADING_STATE = 'SET_SUBSCRIPTIONS_LOADING_STATE'

export const SET_CURRENT_SUBSCRIPTION = 'SET_CURRENT_SUBSCRIPTION'
export const SET_CURRENT_SUBSCRIPTION_LOADING_STATE = 'SET_CURRENT_SUBSCRIPTION_LOADING_STATE'
export const CLEAR_CURRENT_SUBSCRIPTION = 'CLEAR_CURRENT_SUBSCRIPTION'

export const SET_SELECTED_NODE = 'SET_SELECTED_NODE'
export const CLEAR_SELECTED_NODE = 'CLEAR_SELECTED_NODE'

export const SET_PAYMENT_LOADING_STATE = 'SET_PAYMENT_LOADING_STATE'

export const SET_CONNECTION_STATE = 'SET_CONNECTION_STATE'
export const SET_CONNECTION_LOADING_STATE = 'SET_CONNECTION_LOADING_STATE'

export const SET_QUOTA = 'SET_QUOTA'
export const SET_QUOTA_LOADING_STATE = 'SET_QUOTA_LOADING_STATE'
export const CLEAR_QUOTA = 'CLEAR_QUOTA'

export const SET_NODES = 'SET_NODES'
export const SET_NODES_LOADING_STATE = 'SET_NODES_LOADING_STATE'

export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'
export const SET_LOGIN_CHECK_LOADING_STATE = 'SET_LOGIN_CHECK_LOADING_STATE'
export const SET_LOGIN_LOADING_STATE = 'SET_LOGIN_LOADING_STATE'
