export const QUERY_NODE_LIST = 'QUERY_NODE_LIST'
export const QUERY_NODE = 'QUERY_NODE'
export const QUERY_SUBSCRIBED_NODE_LIST = 'QUERY_SUBSCRIBED_NODE_LIST'

export const CONNECT_TO_NODE = 'CONNECT_TO_NODE'
export const DISCONNECT = 'DISCONNECT'
export const QUERY_CONNECTION_STATUS = 'QUERY_CONNECTION_STATUS'
export const QUERY_SERVICE_SERVER = 'QUERY_SERVICE_SERVER'

export const SUBSCRIBE_TO_NODE = 'SUBSCRIBE_TO_NODE'
export const QUERY_QUOTA = 'QUERY_QUOTA'
export const QUERY_CHECKED_QUOTA = 'QUERY_CHECKED_QUOTA'
export const QUERY_SUBSCRIPTION_FOR_NODE = 'QUERY_SUBSCRIPTION_FOR_NODE'
export const QUERY_CHECKED_SUBSCRIPTION_FOR_NODE = 'QUERY_CHECKED_SUBSCRIPTION_FOR_NODE'

export const QUERY_USER = 'QUERY_USER'
export const CREATE_USER = 'CREATE_USER'

export const GET_STORE_VALUE = 'GET_STORE_VALUE'
export const SET_STORE_VALUE = 'SET_STORE_VALUE'

export const QUERY_BALANCES = 'QUERY_BALANCES'

export const OPEN_EXTERNAL_LINK = 'OPEN_EXTERNAL_LINK'
