const QUERY_NODE_LIST = 'QUERY_NODE_LIST'
const QUERY_NODE_INFO = 'QUERY_NODE_INFO'

const CONNECT_TO_NODE = 'CONNECT_TO_NODE'
const DISCONNECT = 'DISCONNECT'

const QUERY_SUBSCRIPTION_LIST = 'QUERY_SUBSCRIPTION_LIST'
const SUBSCRIBE_TO_NODE = 'SUBSCRIBE_TO_NODE'
const QUERY_QUOTA = 'QUERY_QUOTA'
const QUERY_SUBSCRIPTION_FOR_NODE = 'QUERY_SUBSCRIPTION_FOR_NODE'

const CHECK_LOGIN = 'CHECK_LOGIN'
const ADD_ACCOUNT = 'ADD_ACCOUNT'

const GET_STORE_VALUE = 'GET_STORE_VALUE'
const SET_STORE_VALUE = 'SET_STORE_VALUE'

export default [QUERY_NODE_LIST, QUERY_SUBSCRIPTION_LIST, CONNECT_TO_NODE, DISCONNECT, SUBSCRIBE_TO_NODE,
  QUERY_QUOTA, QUERY_SUBSCRIPTION_FOR_NODE, QUERY_NODE_INFO, GET_STORE_VALUE, SET_STORE_VALUE, CHECK_LOGIN, ADD_ACCOUNT
]
